### PR TITLE
fix FileIO deprecation

### PR DESCRIPTION
**Pull request by ExpandingMan**
Getting deprecation warnings from FileIO, here's the fix.

### CODE REVIEW

**Comment by ExpandingMan** [comment]
bump

**Comment by ExpandingMan** [comment]
bump

**Comment by ExpandingMan** [comment]
@eschnett , pinging in case you are not watching the repo

**Comment by eschnett** [comment]
Thanks!

Does this still work with Julia 1.5?

**Comment by ExpandingMan** [comment]
Didn't check 1.5.

**Comment by eschnett** [comment]
1.5 was broken for other reasons anyway, I updated the `compat` section to require 1.6.

**Pull request merged**
